### ISSUE TITLE
How to set the sampling frequency in perf_flamegraph.pxl？

### ISSUE THREAD

**Issue by yeqer** [pixie-io/pixie#1915]
Hello！
I want to use perf_flamegraph.pxl, how can I set the sampling frequency？Are there any related tutorials?

**Comment by ddelnano** [comment]
Hi @yeqer! The perf profiler exposes a command line argument for changing the sampling frequency from its default of 11ms (`--stirling_profiler_stack_trace_sample_period_ms). This can be specified via the [patching mechanism](https://docs.px.dev/reference/admin/deploy-options#deploy-pixie-to-a-subset-of-nodes) exposed to the `px` cli and the helm chart.

Please see our profiler tutorial [here](https://docs.px.dev/tutorials/pixie-101/profiler/). It's easy to get setup with a pixie deployment and the sample application mentioned in that post.

I'm going to close this issue since we want to keep things focused on feature requests, active issues, etc. However, I'm happy to continue discussing the profiler on this thread or in our [community slack](https://slackin.px.dev/)!
