### ISSUE TITLE
Unable to log into withpixie.ai

### ISSUE THREAD

**Issue by ellisio** [pixie-io/pixie#1988]
**Describe the bug**
I attempted to sign up with my email (can disclose if unable to pull from the error ID below), but received an error around the "sending welcome email". Now, I get the following errors on:

Sign Up:
```
Details: ErrorResponse: AADB2C99001: This user already exists, and profile 'AAD-UserWriteUsingAlternativeSecurityId' does not allow the same user to be created again. Correlation ID: 9d931843-3351-489a-924a-62a8d4010e51 Timestamp: 2024-08-21 16:28:57Z
```

Sign In:
```
Details: Failed to login: organization not found, please register.
```

It is also work noting, that after I encountered this, I found work.getcosmic.ai, and was able to register and sign in on that application. However, after installing `px` CLI, the `px auth login` command is always failing because it sends me to `work.withpixie.ai` for all calls.

**To Reproduce**
1. Go to https://work.withpixie.ai/auth/login
2. Click on Login With Google
3. See error

**Expected behavior**
Should be able to login and get things setup.

**Comment by ddelnano** [comment]
Hi @ellisio, the core maintainers are not involved with running that Pixie cloud any longer. @kpattaswamy may be able to help you out with this issue or you can try another cloud from the [hosted pixie](https://docs.px.dev/installing-pixie/install-guides/hosted-pixie/) docs.

I'm happy to continue this discussion here or in the [community slack](https://slackin.px.dev/), but I'm closing this issue since this isn't a problem with the open source project (New Relic hosted cloud).
