### ISSUE TITLE
Is there already exists documentation on how to install pixie with operator or helm?

### ISSUE THREAD

**Issue by ssid334** [pixie-io/pixie#1996]
**Is your feature request related to a problem? Please describe.**
Official documentation provides steps to install pixie with perl+pixie CLI. Is it even possible to install it different way? Like helm charts, crossplane, operator? I see operator image exists, yet I'm unable to find documentation.

**Describe the solution you'd like**
Alternative ways of installation clearly documented.

**Describe alternatives you've considered**
I'm trying to guess operator way of working but the 0.1.6 operator is failing and the CRDs are not installed.

**Additional context**
None

**Comment by ddelnano** [comment]
@ssid334 can you please clarify what you mean by perl+pixie CLI?

Have you see the [helm install docs](https://docs.px.dev/installing-pixie/install-schemes/helm)? Unfortunately that page only documents the most common options. To see what other configuration is possible please see the helm [values.yaml](https://github.com/pixie-io/pixie/blob/4a02aabd7be8a907a2905e9ba69bf17e1ec5d244/k8s/operator/helm/values.yaml) file.

**Comment by ssid334** [comment]
Hey @ddelnano,

thanks for looking into it.

These "helm install docs" are for installing schemes and that is optional step. My understanding this is not for installing pixie, am I mistaken? I see there is operator mentioned there, so I will give it a try.

By "perl+pixie CLI" I mean official way to install it that requires server with perl according to the official documentation :)
![image](https://github.com/user-attachments/assets/37a0a6ee-06db-4ee0-9550-94bfc2f6ef79)

**Comment by ddelnano** [comment]
The "schemes" section refers to how to deploy the vizier Pixie component. If you are looking to install Pixie's vizier to your cluster, those are the helm instructions you'll want to follow.

The schemes section is very similar to the "Install Guides" section. Following either one of those is definitely required if you want to collect data from your environment. I'm not sure exactly what the "(optional)" means in that context, but I'll look into changing that wording since I agree that is confusing.

The docs you linked to are for installing Pixie cloud. Not all users will want to run the cloud themselves since there are hosted options that are easier to manage available.

**Comment by ddelnano** [comment]
@ssid334 I'm going to close this since I believe the existing docs cover this. If you are talking about a helm chart for Pixie cloud, then #431 is the right issue to follow.

If the existing documentation is confusing, I'm happy to make changes but it would be helpful to confirm what part you found confusing.
