### ISSUE TITLE
Alternate options for installation

### ISSUE THREAD

**Issue by kamalrajv** [pixie-io/pixie#246]
**Describe the bug**
On the product page we need to register using a gmail account, is there an alternative for doing it rather than tying it to personal account. 

I am also seeing an issue with accessing the portal after installation where it displays an error for cluster being unavailable. i am not sure if there are any changes that we need to do if we are using aws-auth on our EKS cluster which i don't see as part of documentation.

Appreciate any help on making me understand and use it well.

**Comment by htroisi** [comment]
@kamalrajv - For now, you will need to use a gsuite email in order to sign up a Pixie account. We plan to support more flexible account creation options in the future. 

Regarding the Live UI error for the cluster being unavailable - would you be able to [join our community slack](http://slackin.withpixie.ai/) and post on the #general channel? Our team will probably have an easier time debugging this via a live chat.

**Comment by vihangm** [comment]
The project now supports multiple auth methods. 
- Auth0 with Google OAuth
- Auth0 with Username Password
- Ory Hyrda + Kratos with Username Password

Hopefully these provide enough flexibility to achieve what you want.
