### ISSUE TITLE
Enable JAVA Profiling

### ISSUE THREAD

**Issue by RaymondSteenvoorden** [pixie-io/pixie#275]
Hi,

I would like to do a feature request for java profiling. I think this would be a great addition to Pixie.

Kind regards,

**Comment by yzhao1012** [comment]
(Yaxiong from Pixie team)
Sorry for late reply.

I think you are already played with the existing Pixie profiler: https://docs.pixielabs.ai/tutorials/profiler/ (it does not support Java application profiling, but only the JVM process).

Do you have example of Java profiling you have experienced from the other products available on the market?

Specific features/functionalities you like or dislike from those products would be very helpful as well.

**Comment by antonmry** [comment]
IMHO async profiler is a very complete tool and it could be a good example: https://github.com/jvm-profiling-tools/async-profiler

Also Mission Control is very good: https://github.com/openjdk/jmc

**Comment by oazizi000** [comment]
A quick update for those waiting for Java profiling. The feature is currently in alpha, and we plan to release it after some more testing!

**Comment by htroisi** [comment]
Java support for Pixie's continuous profiler is now in beta. 🎉  

A couple of notes about this beta feature:
- Available for Pixie vizier version 0.10.22+. Learn how to identify and update your vizier version [here](https://docs.px.dev/reference/admin/updating-pixie/#updating-pixie-cloud-and-vizier).
- Java support is a beta feature and must be [manually enabled](https://docs.px.dev/tutorials/pixie-101/profiler/#prerequisites-enabling-java-support).
- For best results, run Java applications with `-XX:+PreserveFramePointer`

Ways to get started:
- [Read the tutorial](https://docs.px.dev/tutorials/pixie-101/profiler/) to see a demo of using Pixie’s continuous profiler to investigate a spike in CPU utilization caused by inefficient application code. Note: this tutorial features Golang application code.
- Run the `px/perf_flamegraph` script in the [Live UI](https://docs.px.dev/using-pixie/using-live-ui/) to see a simple flamegraph that can be filtered by node, namespace, or pod.
- Run the `px/node` script in the Live UI to see a flamegraph for a specific node alongside high-level application metrics (LET) and resource usage. Note: the flamegraph is at the bottom of the page.
- Run the `px/pod` script in the Live UI to see a flamegraph for a specific pod alongside high-level application metrics (LET) and resource usage. Note: the flamegraph is at the bottom of the page.

**Comment by htroisi** [comment]
@etep are there any known limitations with the Pixie profiler Java symbolization?

**Comment by htroisi** [comment]
Quick update for this thread: Support for Java profiling is now included by default in Pixie (no need to manually enable). 🎉

**Comment by c3-pranjaysagar** [comment]
Thanks @htroisi. I have been trying to test Pixie on Java application and for some reason I'm unable to get Java symbolization working?

<img width="287" alt="Screen Shot 2022-09-14 at 6 00 02 PM" src="https://user-images.githubusercontent.com/99224818/190289008-55e061cc-e471-4abb-9053-04368fc57251.png">
<img width="366" alt="Screen Shot 2022-09-14 at 5 59 30 PM" src="https://user-images.githubusercontent.com/99224818/190289023-92f45e9d-fbe6-4754-8542-80ba13072585.png">

**Comment by c3-pranjaysagar** [comment]
@htroisi Confused, did I miss any steps?

**Comment by htroisi** [comment]
@c3-pranjaysagar thanks for reporting this! It looks like @etep responded with some debugging steps on https://github.com/pixie-io/pixie/issues/592, so let's continue the conversation there.

**Comment by asasas234** [comment]
I have no more questions, and by looking at https://blog.px.dev/cpu-profiling-java/#title and https://blog.px.dev/cpu-profiling/ I have roughly understood how the implementation works.
