### ISSUE TITLE
Failed to execute script after EKS update from 1.16 to 1.18

### ISSUE THREAD

**Issue by code-is-art** [pixie-io/pixie#358]
**Describe the bug**
I upgraded EKS from 1.16 to 1.18 and I am now getting failed to execute script errors like "Compiler error on line 211, column 22: Table 'http_events' not found." I have uninstalled and successfully installed px again with no success. All the pixie pods and deployments are running and ready in the cluster. 

**To Reproduce**
1. start with an EKS cluster at 1.16
2. update cluster to 1.17 and create new nodes with the same version and drain the old nodes and delete
3. update cluster to 1.18 and create new nodes with the same version and drain the old nodes and delete
4. check pixie [not working]
5. uninstall and re-install pixie using the cli [not working]

**Screenshots**
![Screen Shot 2021-11-17 at 12 05 11 PM](https://user-images.githubusercontent.com/50637029/142248038-e0e298df-14b7-4013-99bc-a98f20342923.png)

**Logs**
Hannah has the logs

**App information (please complete the following information):**
- Pixie version: 0.7.1+Distribution.04212ae.20211109163321.1
- K8s cluster version: EKS 1.18

**Comment by oazizi000** [comment]
Hi @code-is-art, thanks for reporting.

The issue is related to the kernel version numbering. eBPF is picky and wants an exact match.

Specifically, in this case, Amazon Linux is reporting a `uname -r` of `4.14.252-195.483.amzn2.x86_64`, which corresponds to a Linux version code of 265980. But the actual Linux version code of the kernel is 265983. This prevents the BPF probes from deploying properly.

A workaround is to install the Linux headers on the nodes (e.g. `yum install kernel-headers-4.14.252-195.483.amzn2.x86_64.rpm`), in which case Pixie will get the correct information.

In the meantime, stay tuned as we investigate a fix that doesn't require the workaround.

**Comment by oazizi000** [comment]
16c89ee33c3fd2a738353a0d192a09c8ede67202 resolves this issue.
