### ISSUE TITLE
perf profiler BPF program fails to install

### ISSUE THREAD

**Issue by knfoo** [pixie-io/pixie#380]
**Describe the bug**
Error: "Compiler error on line 324, column 22: Table 'stack_traces.beta' not found."

Environment: 
* kubeadm installed cluster running on baremetal ubuntu 20.04 kernel 5.15

**To Reproduce**
1. deploy px deploy
2. click on script px/pod or px/node

**Expected behavior**
Get pod / node dashboard 

**Screenshots**
![pixie-bug](https://user-images.githubusercontent.com/39614090/147980655-f7725e41-e22e-451d-80d0-b438ace5d673.png)

**Logs**
Please attach the logs by running the following command:
```
./px collect-logs
```
[pixie_logs_20220103200225.zip](https://github.com/pixie-io/pixie/files/7804023/pixie_logs_20220103200225.zip)

**App information (please complete the following information):**
- Pixie version 0.9.16
- K8s cluster version 1.21.5
- Node Kernel version 5.15
- Browser version ff 95.0.1

**Comment by htroisi** [comment]
More context:
- Other scripts are able to run, it's just the ones that use the `stack_traces` table that fail. 
- The pem logs show `E0103 18:28:11.185154 1288697 stirling.cc:357] Source Connector (registry name=perf_profiler) not instantiated, error: Internal : Unable to initialize BCC BPF program: Unable to initialize BPF program`. It appears the per_profiler is the only BPF program that fails.

**Comment by knfoo** [comment]
Our nodes have 512GB memory and is not oft of mem.
I do see some oom on the pem pods.
I can try to increase the pods limits and requests.
Is there an easy way to do that with the operator ?

**Comment by knfoo** [comment]
@etep is there anything else you want me to try or validate ?

**Comment by etep** [comment]
Hi @knfoo,

My current theory is that you have (in some sense) too many CPU cores on your nodes. The size of the BPF shared map for stack traces scales with the number of CPUs. Based on some of the log files, it appears that your machines have 128 cores. While I have not been able to fully reproduce the same issue, the results I have are suggestive.

Based on my experiments, the kernel will refuse to allocate a BPF stack traces table if the size requested is 4M (2^22) or greater. But, I think for a 128 core setup, we will request a table size of 2M. Our requested table size is based on the ratio between our time interval to copy data out of BPF and the underlying stack trace sample period (the number of stack trace samples we expect) and it is scaled up by the number of cores and an expansion factor to provide margin.

I'm guessing you are not running on AWS or GCE, but if so, could you share how to setup an instance that replicates your machine and kernel version?

If you are willing to go down the rabbit hole a little bit, you could try an experiment that reproduces the issue in a more controlled setting. The main idea of this is to create a minimal BPF profiler and then size up its stack traces table until the kernel refuses to allocate. The mechanics of this are very easy because we have such a minimal profiler in our "demos" repo.

Steps to follow:
1. `git clone https://github.com/pixie-io/pixie-demos`
2. `sudo apt install libbpfcc-dev  # also clang, make, golang if not already done`
3. Edit the file `perf_profiler_bpf_funcs.c`:
```
// We will be varying the size of the "stack_traces" table, currently it is 2^21 or 2M
BPF_STACK_TRACE(stack_traces, 1ULL << 21);
BPF_HASH(histogram, struct stack_trace_key_t, uint64_t, 1024);
```
4. `make`
5. `./sqrt &> LOG &`
6. `sudo ./perf_profiler $(pidof sqrt) 5`
7. If that fails, we confirmed 2M is the threshold on your setup, if not, you can bump the table size until it fails.

**Comment by knfoo** [comment]
Hi @etep 

Thank you for your write up of the problem :+1: 

You are right we are running baremetal nodes in our DC.
They have a AMD EPYC 7702P CPU with 128 cores and 512GB mem.

I have run your experiment. It seems to work.
I am not sure how to bump the table size.

I have changed `21` of this: `BPF_STACK_TRACE(stack_traces, 1ULL << 21);` all the way to 28
At 28 the program exit with `could not open bpf map: stack_traces, error: Cannot allocate memory`
The last working value is 27 and if my calc is right that will be 134M ?

Let me know if I need to do more tests.

**Comment by knfoo** [comment]
I have deployed pixie v0.10.2

`px deploy '--patches=vizier-pem:{"spec":{"template":{"spec":{"containers":[{"name":"pem","env":[{"name":"PL_PROFILER_UPDATE_PERIOD","value":"5"}]}]}}}}'`

Now I get data in the UI  thank you.

**Comment by oazizi000** [comment]
As a follow-up, some recent memory optimizations (dedd0032b4c1143798b169a701f4effe552877d9 and 0346961ffc1a615302900a5156ce44745ccb7bb6) should help with high core-count CPUs like you have. There's a good chance you won't need the special `px deploy` flags anymore.
