### ISSUE TITLE
Update ImagePullPolicy to "IfNotPresent" for all deployments/statefulsets

### ISSUE THREAD

**Issue by tuninger** [pixie-io/pixie#530]
It is strongly recommended to change the default value of ImagePullPolicy to "IfNotPresent" in all deployments, statefulset.

**Comment by Sush-Dew** [comment]
@aimichelle @tuninger Could you assign this issue to me? I am a beginner and this issue seems a good first issue to resolve.

**Comment by aimichelle** [comment]
Thanks for offering to pick this up! Let us know if you have any questions about Pixie, or K8s in general. Always happy to help!

**Comment by Sush-Dew** [comment]
Hi, @aimichelle please tell me where to start understanding the bug.

**Comment by aimichelle** [comment]
Whoops, hi @Sush-Dew ! Looks like this was already fixed in https://github.com/pixie-io/pixie/pull/533, so this issue just had not been closed properly. 
If you're still interested in just learning about image pull policies: https://kubernetes.io/docs/concepts/containers/images/#updating-images is a good resource.

Closed by https://github.com/pixie-io/pixie/pull/533.
