### ISSUE TITLE
Support tracing Istio managed services

### ISSUE THREAD

**Issue by yzhao1012** [pixie-io/pixie#578]
**Is your feature request related to a problem? Please describe.**
Today, Pixie’s service map uses remote IP address to derive the Pod name for RPC messages between micro-services. In the case of Istio managed cluster, envoy proxy terminates TCP connections, and RPC messages would use envoy’s address as remote IP. That breaks the logical connection between the client & server, which are mediated by service message proxy.

**Describe the solution you'd like**
Update relevant PXL scripts to replace local IP address `127.0.0.*` with the source pod or service name.

Also support tracing Envoy TLS traffic, by implementing tracing envoy (with boringssl).

**Describe alternatives you've considered**
There is no obvious alternative.

**Additional context**
N/A

**Comment by oazizi000** [comment]
Pixie's tracing with Istio was affected by two issues:
1) The rendering of the service map when accessing local IPs (like localhost or Istio's 127.0.0.6) was broken, because local addresses were being considered as global IPs rather than local to the container they were part of. This would cause service maps that would be incorrect.

This has been fixed by treating localhost addresses in PxL scripts as unique to the pod that they belong to.

2) There are some hops that are missing due to encryption with boringSSL, which is not yet fully supported. This is a separate issue that is not specific to Istio. A separate issue will be filed for this.

**Comment by oazizi000** [comment]
The fixes for this issue rolled out in a number of commits by @yzhao1012 :
2f8613d
c6b21bc
6d24549
d378f8f
3f08697
ce44943

With the fix to the service maps, this issue is considered resolved.
