### ISSUE TITLE
px/cluster: "Namespaces" table only shows a subset of actual namespaces due to PxL script bug

### ISSUE THREAD

**Issue by nserrino** [pixie-io/pixie#604]
**Describe the bug**
The namespaces table in px/cluster (and possibly other views) does an inner join with a services table and a HTTP requests table. For namespaces that don't have any services, or namespaces that haven't received any HTTP requests in the time window, they will be omitted from this view.

We should change these joins to left/right so that there are still results for these types of namespaces.

Also, we should audit existing scripts to ensure we don't use inner join in the wrong places elsewhere.

**Comment by philkuz** [comment]
Had a chance to check this out and the bug that you saw is not caused by the inner join in that part of the script. We highly suspect that 1 of 2 things happened:
1. You ran into #534 which has recently been fixed
2. Namespaces that didn't have services also don't have pods so we don't collect data on the namespace.
