### ISSUE TITLE
create-admin-job is missing

### ISSUE THREAD

**Issue by dborysenko** [pixie-io/pixie#653]
**Describe the bug**
Tried to install pixie cloud and found that create-admin-job was never created. Found below commit which is included in the latest tag, can it be the reason why job is missing? If so, what is the correct way to get credentials for admin user for freshly installed cloud?
https://github.com/pixie-io/pixie/commit/3402b495fdaf8d1e3faededc04e973c0fb83efc6#diff-fc2a310fcfedfefb0046def697f932def80cbb1e78c689bc0af3c8eab3e33ece

**To Reproduce**
Follow below instructions, after step 13 try to look for "create-admin-job"
https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#1.-deploy-pixie-cloud

**Expected behavior**
create-admin-job is expected to provide a way for first time login.

**App information (please complete the following information):**
- Pixie version LATEST_CLOUD_RELEASE=1668540618
- K8s cluster version 1.23
- Node Kernel version
- Browser version Chrome 107.0.5304.110 

**Additional context**

**Comment by htroisi** [comment]
@dborysenko - we recently changed the self-hosted install flow to remove the manual step of setting the admin password (which is why this job has been deleted). The default admin password is now set for you ([commit](https://github.com/pixie-io/pixie/commit/cb9cfe569f524584f268eb038e56709352bb9619)). Simply login into the `admin@default.com` account with `admin` as the password. 

New directions here: https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#1.-deploy-pixie-cloud-authentication-using-kratos-hydra

**Comment by dborysenko** [comment]
Great, must have missed updated documentation.
Closing. Thank you.

**Comment by tshiyuoo** [comment]
@htroisi   when  visit Pixie login page , page error: Cannot read properties of undefined (reading 'password'), How to fix it?

**Comment by htroisi** [comment]
@tshiyuoo it looks like Phillip answered your question on our community Slack. Did re-deploying Pixie with the latest cloud release fix the issue for you?
