### ISSUE TITLE
Deflake `redis_trace_bpf_test`

### ISSUE THREAD

**Issue by vihangm** [pixie-io/pixie#696]
`//src/stirling/source_connectors/socket_tracer:redis_trace_bpf_test` has a <90% pass rate in CI.
De-flake the test, run locally with `runs_per_test` set to a large number to ensure that the pass rate is higher than 90% and then re-enable the test in CI by removing the `disabled_flaky_test` tag.

**Comment by ddelnano** [comment]
I looked into this yesterday and the test failures in buildbuddy and what I've reproduced myself fit into two buckets with their respective error logs listed below:
- Redis returning denyoom error responses rather than the expected responses. Redis returns this if the server's memory is too high (compared to the [maxmemory](https://redis.io/commands/command/) configuration)
<details><summary>failed output</summary>

```
src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc:164 Value of: redis_trace_records Expected: has 19 elements where element #0 is equal to cmd: PING req: {"message":"test"} resp: test, element #1 is equal to cmd: SET req: {"key":"foo","value":"100","options":["EX 10","NX"]} resp: OK, element #2 is equal to cmd: EXPIRE req: {"key":"foo","seconds":"10000"} resp: 1, element #3 is equal to cmd: BITCOUNT req: ["foo","0","0"] resp: 3, element #4 is equal to cmd: INCR req: {"key":"foo"} resp: 101, element #5 is equal to cmd: APPEND req: {"key":"foo","value":"xxx"} resp: 6, element #6 is equal to cmd: GET req: {"key":"foo"} resp: 101xxx, element #7 is equal to cmd: MGET req: {"key":["foo","bar"]} resp: ["101xxx","<NULL>"], element #8 is equal to cmd: SADD req: {"key":"myset","member":["1","2","3"]} resp: 3, element #9 is equal to cmd: SSCAN req: {"key":"myset","cursor":"0","pattern":"[a-z]+","count":"10"} resp: ["0","[]"], element #10 is equal to cmd: SCARD req: {"key":"myset"} resp: 3, element #11 is equal to cmd: SMEMBERS req: {"key":"myset"} resp: ["1","2","3"], element #12 is equal to cmd: HMSET req: {"key":"fooset","field value":[{"field":"f1"},{"value":"100"},{"field":"f2"},{"value":"200"}]} resp: OK, element #13 is equal to cmd: HMGET req: {"key":"fooset","field":["f1","f2"]} resp: ["100","200"], element #14 is equal to cmd: HGET req: {"key":"fooset","field":"f1"} resp: 100, element #15 is equal to cmd: HGETALL req: {"key":"fooset"} resp: ["f1","100","f2","200"], element #16 is equal to cmd: WATCH req: {"key":["foo","bar"]} resp: OK, element #17 is equal to cmd: UNWATCH req: [] resp: OK, element #18 is equal to cmd: SELECT req: {"index":"0"} resp: OK Actual: { cmd: TOUCH req: {"key":["-2","[\"fast\"]","1","-1","1","[\"@keyspace\",\"@read\",\"@fast\"]"]} resp: , cmd: ZREMRANGEBYSCORE req: {"key":"4","min":"[\"write\"]","max":"1"} resp: , cmd: RESTORE req: ["-4","[\"write\",\"denyoom\"]","1","1","1","[\"@keyspace\",\"@write\",\"@slow\",\"@dangerous\"]"] resp: , cmd: DUMP req: {"key":"2"} resp: , cmd: RPOPLPUSH req: {"source":"3","destination":"[\"write\",\"denyoom\"]"} resp: , cmd: DBSIZE req: ["1","[\"fast\"]","0","0","0","[\"@keyspace\",\"@read\",\"@fast\"]"] resp: , cmd: UNSUBSCRIBE req: ["-1","[\"noscript\",\"loading\",\"stale\"]","0","0","0","[\"@pubsub\",\"@slow\"]"] resp: , cmd: GEODIST req: ["-4","[]","1","1","1","[\"@read\",\"@geo\",\"@slow\"]"] resp: , cmd: MSET req: {"key value":[{"key":"-3"},{"value":"[\"write\",\"denyoom\"]"},{"key":"1"},{"value":"-1"},{"key":"2"},{"value":"[\"@write\",\"@string\",\"@slow\"]"}]} resp: , cmd: LTRIM req: {"key":"4","start":"[\"write\"]","stop":"1"} resp: , cmd: HSET req: ["-4","[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@hash\",\"@fast\"]"] resp: , cmd: ZSCORE req: {"key":"3","member":"[\"fast\"]"} resp: , cmd: XLEN req: {"key":"2"} resp: , cmd: SDIFFSTORE req: {"destination":"-3","key":["[\"write\",\"denyoom\"]","1","-1","1","[\"@write\",\"@set\",\"@slow\"]"]} resp: , cmd: RPOP req: {"key":"-2","count":"[\"write\",\"fast\"]"} resp: , cmd: RENAME req: {"key":"3","newkey":"[\"write\"]"} resp: , cmd: COMMAND req: [] resp: ["config","-2","[\"admin\",\"noscript\",\"loading\",\"stale\"]","0","0","0","[\"@admin\",\"@slow\",\"@dangerous\"]"], cmd: DEL req: {"key":["-2","[\"write\"]","1","-1","1","[\"@keyspace\",\"@write\",\"@slow\"]"]} resp: , cmd: SADD req: {"key":"-3","member":["[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@set\",\"@fast\"]"]} resp: , cmd: ZREVRANGEBYSCORE req: ["-4","[]","1","1","1","[\"@read\",\"@sortedset\",\"@slow\"]"] resp: , cmd: SET req: {"key":"-3","value":"[\"write\",\"denyoom\"]","options":["1","1","1","[\"@write\",\"@string\",\"@slow\"]"]} resp: , cmd: BITOP req: {"operation":"-4","destkey":"[\"write\",\"denyoom\"]","key":["2","-1","1","[\"@write\",\"@bitmap\",\"@slow\"]"]} resp: , cmd: ZINTERSTORE req: ["-4","[\"write\",\"denyoom\",\"movablekeys\"]","1","1","1","[\"@write\",\"@sortedset\",\"@slow\"]"] resp: , cmd: PUBSUB req: ["-2","[\"random\",\"loading\",\"stale\"]","0","0","0","[\"@pubsub\",\"@slow\"]"] resp: , cmd: HMSET req: ["-4","[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@hash\",\"@fast\"]"] resp: , cmd: HRANDFIELD req: ["-2","[\"random\"]","1","1","1","[\"@read\",\"@hash\",\"@slow\"]"] resp: , cmd: ZCARD req: {"key":"2"} resp: , cmd: BITFIELD req: ["-2","[\"write\",\"denyoom\"]","1","1","1","[\"@write\",\"@bitmap\",\"@slow\"]"] resp: , cmd: ZRANGESTORE req: ["-5","[\"write\",\"denyoom\"]","1","2","1","[\"@write\",\"@sortedset\",\"@slow\"]"] resp: , cmd: HELLO req: ["-1","[\"noscript\",\"loading\",\"stale\",\"skip_monitor\",\"skip_slowlog\",\"fast\",\"no_auth\"]","0","0","0","[\"@fast\",\"@connection\"]"] resp: , cmd: DISCARD req: ["1","[\"noscript\",\"loading\",\"stale\",\"fast\"]","0","0","0","[\"@fast\",\"@transaction\"]"] resp: , cmd: RPUSHX req: {"key":"-3","element":["[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@list\",\"@fast\"]"]} resp: , ... }, which has 222 elements
src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc:164
Value of: redis_trace_records
Expected: has 19 elements where
element #0 is equal to cmd: PING req: {"message":"test"} resp: test,
element #1 is equal to cmd: SET req: {"key":"foo","value":"100","options":["EX 10","NX"]} resp: OK,
element #2 is equal to cmd: EXPIRE req: {"key":"foo","seconds":"10000"} resp: 1,
element #3 is equal to cmd: BITCOUNT req: ["foo","0","0"] resp: 3,
element #4 is equal to cmd: INCR req: {"key":"foo"} resp: 101,
element #5 is equal to cmd: APPEND req: {"key":"foo","value":"xxx"} resp: 6,
element #6 is equal to cmd: GET req: {"key":"foo"} resp: 101xxx,
element #7 is equal to cmd: MGET req: {"key":["foo","bar"]} resp: ["101xxx","<NULL>"],
element #8 is equal to cmd: SADD req: {"key":"myset","member":["1","2","3"]} resp: 3,
element #9 is equal to cmd: SSCAN req: {"key":"myset","cursor":"0","pattern":"[a-z]+","count":"10"} resp: ["0","[]"],
element #10 is equal to cmd: SCARD req: {"key":"myset"} resp: 3,
element #11 is equal to cmd: SMEMBERS req: {"key":"myset"} resp: ["1","2","3"],
element #12 is equal to cmd: HMSET req: {"key":"fooset","field value":[{"field":"f1"},{"value":"100"},{"field":"f2"},{"value":"200"}]} resp: OK,
element #13 is equal to cmd: HMGET req: {"key":"fooset","field":["f1","f2"]} resp: ["100","200"],
element #14 is equal to cmd: HGET req: {"key":"fooset","field":"f1"} resp: 100,
element #15 is equal to cmd: HGETALL req: {"key":"fooset"} resp: ["f1","100","f2","200"],
element #16 is equal to cmd: WATCH req: {"key":["foo","bar"]} resp: OK,
element #17 is equal to cmd: UNWATCH req: [] resp: OK,
element #18 is equal to cmd: SELECT req: {"index":"0"} resp: OK
  Actual: { cmd: TOUCH req: {"key":["-2","[\"fast\"]","1","-1","1","[\"@keyspace\",\"@read\",\"@fast\"]"]} resp: , cmd: ZREMRANGEBYSCORE req: {"key":"4","min":"[\"write\"]","max":"1"} resp: , cmd: RESTORE req: ["-4","[\"write\",\"denyoom\"]","1","1","1","[\"@keyspace\",\"@write\",\"@slow\",\"@dangerous\"]"] resp: , cmd: DUMP req: {"key":"2"} resp: , cmd: RPOPLPUSH req: {"source":"3","destination":"[\"write\",\"denyoom\"]"} resp: , cmd: DBSIZE req: ["1","[\"fast\"]","0","0","0","[\"@keyspace\",\"@read\",\"@fast\"]"] resp: , cmd: UNSUBSCRIBE req: ["-1","[\"noscript\",\"loading\",\"stale\"]","0","0","0","[\"@pubsub\",\"@slow\"]"] resp: , cmd: GEODIST req: ["-4","[]","1","1","1","[\"@read\",\"@geo\",\"@slow\"]"] resp: , cmd: MSET req: {"key value":[{"key":"-3"},{"value":"[\"write\",\"denyoom\"]"},{"key":"1"},{"value":"-1"},{"key":"2"},{"value":"[\"@write\",\"@string\",\"@slow\"]"}]} resp: , cmd: LTRIM req: {"key":"4","start":"[\"write\"]","stop":"1"} resp: , cmd: HSET req: ["-4","[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@hash\",\"@fast\"]"] resp: , cmd: ZSCORE req: {"key":"3","member":"[\"fast\"]"} resp: , cmd: XLEN req: {"key":"2"} resp: , cmd: SDIFFSTORE req: {"destination":"-3","key":["[\"write\",\"denyoom\"]","1","-1","1","[\"@write\",\"@set\",\"@slow\"]"]} resp: , cmd: RPOP req: {"key":"-2","count":"[\"write\",\"fast\"]"} resp: , cmd: RENAME req: {"key":"3","newkey":"[\"write\"]"} resp: , cmd: COMMAND req: [] resp: ["config","-2","[\"admin\",\"noscript\",\"loading\",\"stale\"]","0","0","0","[\"@admin\",\"@slow\",\"@dangerous\"]"], cmd: DEL req: {"key":["-2","[\"write\"]","1","-1","1","[\"@keyspace\",\"@write\",\"@slow\"]"]} resp: , cmd: SADD req: {"key":"-3","member":["[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@set\",\"@fast\"]"]} resp: , cmd: ZREVRANGEBYSCORE req: ["-4","[]","1","1","1","[\"@read\",\"@sortedset\",\"@slow\"]"] resp: , cmd: SET req: {"key":"-3","value":"[\"write\",\"denyoom\"]","options":["1","1","1","[\"@write\",\"@string\",\"@slow\"]"]} resp: , cmd: BITOP req: {"operation":"-4","destkey":"[\"write\",\"denyoom\"]","key":["2","-1","1","[\"@write\",\"@bitmap\",\"@slow\"]"]} resp: , cmd: ZINTERSTORE req: ["-4","[\"write\",\"denyoom\",\"movablekeys\"]","1","1","1","[\"@write\",\"@sortedset\",\"@slow\"]"] resp: , cmd: PUBSUB req: ["-2","[\"random\",\"loading\",\"stale\"]","0","0","0","[\"@pubsub\",\"@slow\"]"] resp: , cmd: HMSET req: ["-4","[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@hash\",\"@fast\"]"] resp: , cmd: HRANDFIELD req: ["-2","[\"random\"]","1","1","1","[\"@read\",\"@hash\",\"@slow\"]"] resp: , cmd: ZCARD req: {"key":"2"} resp: , cmd: BITFIELD req: ["-2","[\"write\",\"denyoom\"]","1","1","1","[\"@write\",\"@bitmap\",\"@slow\"]"] resp: , cmd: ZRANGESTORE req: ["-5","[\"write\",\"denyoom\"]","1","2","1","[\"@write\",\"@sortedset\",\"@slow\"]"] resp: , cmd: HELLO req: ["-1","[\"noscript\",\"loading\",\"stale\",\"skip_monitor\",\"skip_slowlog\",\"fast\",\"no_auth\"]","0","0","0","[\"@fast\",\"@connection\"]"] resp: , cmd: DISCARD req: ["1","[\"noscript\",\"loading\",\"stale\",\"fast\"]","0","0","0","[\"@fast\",\"@transaction\"]"] resp: , cmd: RPUSHX req: {"key":"-3","element":["[\"write\",\"denyoom\",\"fast\"]","1","1","1","[\"@write\",\"@list\",\"@fast\"]"]} resp: , ... }, which has 222 elements
```

</details>

- [Redis VerifyCommand](https://github.com/pixie-io/pixie/blob/0702201026240aa03006ac4d6c7c9d06f1772b2c/src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc#L253) test fails due to lack of data in the redis table
<details><summary>failed output</summary>

```
src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc:253 Expected equality of these values: tablets.size() Which is: 0 1
src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc:253
Expected equality of these values:
  tablets.size()
    Which is: 0
  1
```

</details>

The redis memory pressure issues account for 9 out of the 12 test failures over the last week the test was still running in CI, so that is the bulk of the failures.

For the denyoom issue, I verified that the redis docker container used in the test doesn't have a `redis.conf` specified and so we should be falling back to the `maxmemory` default of 0, which means unlimited. I reproduced the issue on a gcp instance that is configured similar to our [jenkins agents](https://github.com/pixie-io/pixie/blob/0702201026240aa03006ac4d6c7c9d06f1772b2c/ci/bpf/00_create_instance.sh#L52-L65). These instances have 62 GB of memory and so it's surprising that the unlimited memory default would experience memory pressure.

We are running these tests in docker through bazel and it appears we set bazel's `--local_ram_resources` to [40,000 MB](https://github.com/pixie-io/pixie/blob/0702201026240aa03006ac4d6c7c9d06f1772b2c/ci/jenkins.bazelrc#LL33C8-L33C27). I used `ps` to print out the memory usage of the redis process while running these tests and it appeared to be in the virtual memory and RSS were consistently ~50 MB and ~12 MB respectively.

<details><summary>Memory output</summary>
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.4  0.0  52960 13164 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886184  0.0  0.0   5268  2316 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.8  0.0  52960 13164 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886186  0.0  0.0   5268  2320 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.6  0.0  52960 13164 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886188  0.0  0.0   5268  2280 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.5  0.0  52960 13164 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886190  0.0  0.0   5268  2320 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.5  0.0  52960 13164 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886192  0.0  0.0   5268  2336 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.4  0.0  52960 13164 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886195  0.0  0.0   5268  2340 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.4  0.0  52960 13228 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886198  0.0  0.0   5268  2336 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.4  0.0  52960 13228 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886400  0.0  0.0   5268  2316 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.4  0.0  52960 13228 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886435  0.0  0.0   5268  2276 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886092  0.4  0.0  52960 13228 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886437  0.0  0.0   5268  2328 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
ddelnano  886515  0.0  0.0   5268  2340 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  886627  0.0  0.0  52960 11096 ?        Ssl  15:15   0:00 redis-server *:6379
ddelnano  886707  0.0  0.0   5268  2320 pts/0    S+   15:15   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  2.0  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894653  0.0  0.0   5268  2340 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  1.0  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894655  0.0  0.0   5268  2332 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  0.6  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894657  0.0  0.0   5268  2308 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  0.7  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894659  0.0  0.0   5268  2384 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  0.5  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894692  0.0  0.0   5268  2336 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  0.6  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894694  0.0  0.0   5268  2388 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  0.5  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894696  0.0  0.0   5268  2264 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  0.5  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894698  0.0  0.0   5268  2320 pts/0    S+   15:20   0:00 grep redis-server
ddelnano@ddelnano-test-machine:~$ ps auxww | grep redis-server
systemd+  894572  0.4  0.0  52960 11116 ?        Ssl  15:19   0:00 redis-server *:6379
ddelnano  894828  0.0  0.0   5268  2332 pts/0    S+   15:20   0:00 grep redis-server
</details>

I tried changing bazel's test size for this test to enormous since that informs bazel how much memory it should expect the test to use at peak. This unfortunately did not have any impact in the stability of the build. I'm wondering if there is some other memory limit being applied, maybe some control group is limiting bazel from using the 40,000MB that we expect? I'll continuing to investigate the source of this memory pressure, but that's what I discovered thus far.

As for the second issue, I haven't spent any time investigating it. Since the memory issue accounts for the vast majority of failures, I will look into this once the first issue is solved.

**Comment by ddelnano** [comment]
I initially thought the redis container was returning denyoom responses, but later discovered this is due to the redis-cli's command req. Our test tries to [erase](https://github.com/pixie-io/pixie/blob/d0e38daeab4cbd8f4fe91d728f634fc654b19607/src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc#L127-L136) these records, but it appears to be unsuccessful in certain cases.

Our previous test assertion required that we received an extremely strict number of traces and order, so when the command req erasing fails the test flakes. I have a code review open that introduces a new assertion (`ContainsWithRelativeOrder`) that will ensure the expected traces are in order, but does not require the 'array' to have an exact match (length and element positioning).
