### ISSUE TITLE
Deflake `pgsql_trace_bpf_test`

### ISSUE THREAD

**Issue by vihangm** [pixie-io/pixie#697]
`//src/stirling/source_connectors/socket_tracer:pgsql_trace_bpf_test` has a <90% pass rate in CI.
De-flake the test, run locally with `runs_per_test` set to a large number to ensure that the pass rate is higher than 90% and then re-enable the test in CI by removing the `disabled_flaky_test` tag.

**Comment by ddelnano** [comment]
The source of the flakiness is due to how the pgsql stitcher works. It previously assumed that when it sees a request that the matching response exists during the same invocation to StitchFrames. For our test harness, this is true the majority of the time. However, there are times where stirling sees the request in isolation, calls StitchFrames and then receives the response by the second call to StitchFrames. The previous stitcher implementation discards all requests at the [end of a run](https://github.com/pixie-io/pixie/blob/28a762a31673ee2e3956693df7871393bcacf156/src/stirling/source_connectors/socket_tracer/protocols/pgsql/stitcher.cc#L462), so when this happens we lose the request and can never match the lone response on the next StitchFrames invocation. This results in all of the test cases occasionally seeing the following error:

```
	src/stirling/source_connectors/socket_tracer/pgsql_trace_bpf_test.cc:219: Failure
Expected equality of these values:
  tablets.size()
    Which is: 0
  1
```

While this test was flaky, this detected a real bug in our stitcher and further demonstrates why having a true end to end test is valuable even if it's not as reproducible.

I have a phab open for this and verified that the test passes 20/20 times, so we should be able to re-enable this test shorly
