### ISSUE TITLE
Deflake `grpc_trace_bpf_test`

### ISSUE THREAD

**Issue by vihangm** [pixie-io/pixie#698]
`//src/stirling/source_connectors/socket_tracer:grpc_trace_bpf_test` has a <90% pass rate in CI.
De-flake the test, run locally with `runs_per_test` set to a large number to ensure that the pass rate is higher than 90% and then re-enable the test in CI by removing the `disabled_flaky_test` tag.

**Comment by ddelnano** [comment]
@orishuss is this something you'd be interested in helping to fix? I've taken a few hours to investigate it, but don't have any leads on the source of the flake so far. We'd like to get this test enabled as soon as it's stabilized, but I'm focusing my attention on other flaky tests in the meantime since they are lower hanging fruit.

**Comment by orishuss** [comment]
Hey @ddelnano :) As we discussed on slack a couple of weeks back, this is a Golang-gRPC test issue, and unfortunately I am not as familiar with this area as with the gRPC-c module.

**Comment by ddelnano** [comment]
@orishuss upon looking at this again, the test failure is in the [grpc_trace_bpf_test](https://github.com/pixie-io/pixie/blob/e3b66578dc16fc20a37d91ea99d2304062960930/src/stirling/source_connectors/socket_tracer/grpc_trace_bpf_test.cc#L208) is actually a python test verifying the grpc-c functionality Ground cover worked on (see linked pull request for more details). It may not be familiar because it seems that Yaxiong contributed the end to end test (https://github.com/pixie-io/pixie/commit/c189051ed9c74e6a10bfec9a946cc4159241cb74).

We got lucky that the switch to podman has stabilized the test, and unblocks us from re-enabling it. However, the underlying cause of the grpc-c protocol tracing still needs to be investigated (#920). The other flaky tests we disabled in this batch had real parsing and stitching issues (https://github.com/pixie-io/pixie/issues/696, https://github.com/pixie-io/pixie/issues/697), so I think there is a chance there is some edge case that isn't addressed causing that instability.
